spring:
  profiles:
    active: product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.2.152:3306/itsm_4614?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: UTC
server:
  port: 80

